### PR TITLE
Allowing config of data loader

### LINKED ISSUE #4: Is dataloader configurable?
Hi!

Playing around with this package. I'm enjoying it a lot so far!

I was wondering, is it possible for you to expose DataLoader's configuration. I want to look into [scheduling](https://github.com/graphql/dataloader#batch-scheduling) and it doesn't seem like this is currently possible.

Thanks!

### PR DESCRIPTION
**Pull request by zekenie**
Hi @TreeMan360,

I made a PR with the change. I also noticed that types weren't working in my project because the `types` field on the package.json was not referencing the dist directory. When I fixed that, I got a new error (in my app, the package consumer), that I don't quite follow. I believe this ts error already existed but was covered up by the types not exporting. I figured I'd get your thoughts now in case you understand the error before trying to diagnose further.

```
node_modules/nestjs-graphql-dataloader/dist/index.d.ts:11:5 - error TS2416: Property 'intercept' in type 'DataLoaderInterceptor' is not assignable to the same property in base type 'NestInterceptor<any, any>'.
  Type '(context: ExecutionContext, next: CallHandler<any>) => Observable<any>' is not assignable to type '(context: ExecutionContext, next: CallHandler<any>) => Observable<any> | Promise<Observable<any>>'.
    Type 'Observable<any>' is not assignable to type 'Observable<any> | Promise<Observable<any>>'.
      Type 'import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/nestjs-graphql-dataloader/node_modules/rxjs/internal/Observable").Observable<any>' is not assignable to type 'import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/rxjs/internal/Observable").Observable<any>'.
        The types of 'operator.call' are incompatible between these types.
          Type '(subscriber: import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/nestjs-graphql-dataloader/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/nestjs-graphql-dataloader/node_modules/rxjs/internal/types")....' is not assignable to type '(subscriber: import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/rxjs/internal/types").TeardownLogic'.
            Types of parameters 'subscriber' and 'subscriber' are incompatible.
              Type 'import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/rxjs/internal/Subscriber").Subscriber<any>' is not assignable to type 'import("/Users/zekenierenberg/Documents/Code/frank/backend/node_modules/nestjs-graphql-dataloader/node_modules/rxjs/internal/Subscriber").Subscriber<any>'.
                Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.

11     intercept(context: ExecutionContext, next: CallHandler): Observable<any>;
       ~~~~~~~~~
```

### CODE REVIEW

**Comment by zekenie** [comment]
@TreeMan360 I believe this may be an issue with how I was testing it? See [this post on SO](https://stackoverflow.com/questions/38168581/observablet-is-not-a-class-derived-from-observablet). I copied the dist directory from the package into my project.... I'm not sure if it's a real issue.

**Comment by zekenie** [comment]
@TreeMan360 when I installed rxjs 6.5.4 in my app the error went away

**Review by TreeMan360 — APPROVED** [review]
👍 😎

**Comment by TreeMan360** [comment]
Thanks for this. Yes sorry I really just quickly pulled this package out from my mono-repo and didn't give it any TLC so it's not exactly in the ideal state for contributions in all honesty. Needs some tidying up, tests and a CI script.

Thanks for your contribution! Sorry I wasn't available to answer your queries during dev.

**Pull request merged**
